name: Run Unit Tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup .NET 8.0
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'

    - name: Restore dependencies
      run: dotnet restore Grocery.sln

    - name: Build solution
      run: dotnet build Grocery.sln --no-restore

    - name: Run unit tests and generate TRX report
      run: dotnet test Grocery.sln --no-build --logger "trx;LogFileName=results.trx" --results-directory "TestResults"

    - name: Upload test results
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: test-results
        path: TestResults/*.trx
